#-------------------------------
# General Site Settings

title: Vasant Wankhede
description: Painter // Artist // Director
email: vasantwankhede234@outlook.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About, url: '#about'}
- {name: Work, url: '#work'}
- {name: Testimonials, url: '#testimonials'}
- {name: Enquiries, url: '#enquiries'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

#seo:
#   description: 'Provide a description for your website to make it visible to search engines.'
#   rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
#   rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Travis specializes in making things** for human people.
  Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen.

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# testimonials Section

testimonials:
- {avatar: 'FFFFFF-1.png',
  name: 'The Telegraph',
  title: '<a href="https://www.telegraphindia.com/1100117/jsp/calcutta/story_11989244.jsp">See through gauze</a>',
  quote: '<p><strong>His works created with layers of textile</strong> in faded shades of blue, buff, grey and ochre, often with a dash of red running across their rectangular expanse, are meditative and tranquil that have no parallels in the visible world.</p>',
  logo: 'logo1.png'}
- {avatar: 'FFFFFF-1.png',
  name: 'Bodhana Foundation',
  title: '<a href="http://bodhana.org/products/breath-of-visual-fiber.aspx">Breath of Visual Fiber</a>',
  quote: '<p>Veteran painter Vasant Wankhede belongs to the generation of painters who believed that the true meaning of ‘spiritual’ is nothing but <strong>having faith in your creative deeds</strong> and following these under the guru’s blessings.</p>',
  logo: 'logo2.png'}
- {avatar: 'FFFFFF-1.png',
  name: 'Mid-day',
  title: '<a href="https://www.mid-day.com/articles/mumbai-diary-tuesday-dossier/16668196">A bandage for the art world</a>',
  quote: '<p>In a <strong>career spanning four decades</strong> (1965 onwards), Wankhede’s oeuvre comprised black-and-white water-colour works, canvas paintings, collages as well as abstract art using media like bandage and cloth. This became his trademark style.</p>',
  logo: 'logo3.jpg'}

#-------------------------------
# enquiries Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
